config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :carts
    resources :favorites
    resources :line_items
    resources :orders
    resources :orders_users
    resources :products

    root to: "users#index"
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "products#index"
  resources :products
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: :create
  resources :favorites, only: [:create, :destroy]
  resources :images, only: :destroy
  resources :avatars, only: :destroy
  namespace :my do
    resource :cart, only: [:show]
    resources :orders, only: [:index, :show]
    resources :sales_orders, only: [:index, :show]
    resources :favorite_sellers, only: :index
    resources :favorite_products, only: :index
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :buyer, class_name: 'User', foreign_key: :user_id
  has_many :line_items
  has_many :products, through: :line_items

  def total_price
    line_items.inject(0) { |sum, item| sum + item.price * item.quantity }
  end
end

app/controllers/admin/carts_controller.rb
module Admin
  class CartsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Cart.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Cart.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/my/carts_controller.rb
module My
  class CartsController < ApplicationController
    include MyConcern

    def show
      @cart = current_user.cart
      @line_items = @cart&.line_items
    end
  end
end

app/controllers/my/favorite_products_controller.rb
module My
  class FavoriteProductsController < ApplicationController
    include MyConcern

    def index
      @favorite_products =
        current_user.favorite_products.page(params[:page]).per(10)
    end
  end
end

app/controllers/my/favorite_sellers_controller.rb
module My
  class FavoriteSellersController < ApplicationController
    include MyConcern

    def index
      @favorite_sellers =
        current_user.favorite_sellers.page(params[:page]).per(10)
    end
  end
end

app/controllers/my/orders_controller.rb
module My
  class OrdersController < ApplicationController
    include MyConcern

    def index
      @orders = current_user.orders.page(params[:page]).per(5)
    end

    def show
      @order = current_user.orders.find params[:id]
    end
  end
end

app/controllers/my/sales_orders_controller.rb
module My
  class SalesOrdersController < ApplicationController
    include MyConcern

    def index
      @sales_orders = current_user.sales_orders.page(params[:page]).per(5)
    end
  end
end

app/views/my/carts/_cart_row.html.erb
<div class="row">
  <div class="col-md-3">
    <h4><%= item.product_name %></h4>
  </div>
  <div class="col-md-9">
    <%= form_for item, remote: true do |f| %>
      <div class='form-row'>
        <div class='col-md-3'>
          <%= f.number_field :quantity, class: "form-control", min: 1 %>
          <%= f.hidden_field :product_id, value: item.product_id %>
        </div>
        <div class='col-md-6'>
          <div class='btn-group'>
            <%= f.submit "Update quantity", class: "btn btn-outline-secondary btn-sm" %>
            <%= link_to "Delete", item, { data: { confirm: "Sure?" }, method: :delete, remote: true, class: "btn btn-outline-danger btn-sm" } %>
          </div>
        </div>
        <div class='col-md-3'>
          <%= number_to_currency item.sum_price %> pt
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/my/carts/_shopping_cart.html.erb
<h3>Your cart</h3>
<% if current_user.cart %>
  <% @line_items.each do |item| %>
    <%= render 'my/carts/cart_row', item: item %>
  <% end %>
  <div class="row">
    <div class="col-md-4 offset-md-8">
      <h4 class="text-right">Total price: <%= number_to_currency @cart.total_price %></h4>
    </div>
  </div>
  <%= link_to 'Purchase', orders_path, method: :post, class: 'btn btn-primary' %>
<% else %>
  <h2>Nothing in the cart.</h2>
<% end %>

app/views/my/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>