config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :carts
    resources :favorites
    resources :line_items
    resources :orders
    resources :orders_users
    resources :products

    root to: "users#index"
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "products#index"
  resources :products
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: :create
  resources :favorites, only: [:create, :destroy]
  resources :images, only: :destroy
  resources :avatars, only: :destroy
  namespace :my do
    resource :cart, only: [:show]
    resources :orders, only: [:index, :show]
    resources :sales_orders, only: [:index, :show]
    resources :favorite_sellers, only: :index
    resources :favorite_products, only: :index
  end
end

app/models/product.rb
class Product < ApplicationRecord
  extend Enumerize
  include Favorable
  # searchkick mappings {
  #   product: {
  #     properties: {
  #       description: { type: 'string', norms: { enabled: false } }
  #     }
  #   }
  # }
  searchkick callbacks: :async

  enumerize :status, in: { draft: 0, published: 1 },
            default: :draft, scope: true

  validates :name, presence: true
  validates :price, presence: true

  belongs_to :seller, class_name: 'User', foreign_key: :user_id
  has_many_attached :images

  delegate :email, to: :seller, prefix: 'seller'

  after_save { Product.reindex }

  # def should_index?
  #   status == 'published'
  # end

  def search_data
    {
      name: name,
      description: description,
      status: status
    }
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:keywords].present?
      @products = Product.search(
                           params[:keywords],
                           fields: ['name^10', 'description'],
                           operator: 'or',
                           includes: [:seller, images_attachments: :blob],
                           where: { status: 'published' },
                           page: params[:page],
                           per_page: 20
                          )
    else
      @products = Product.with_status(:published)
                         .includes(:seller, images_attachments: :blob)
                         .page(params[:page]).per(5)
    end
  end

  def show
    @line_item = LineItem.new
  end

  def new
    @product = current_user.products.build
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    authorize @product
  end

  def update
    authorize @product
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to products_path
  end

  private

  def find_product
    @product = Product.with_attached_images.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name, :description, :price, :status, :quantity, images: []
    )
  end
end

app/views/products/_form.html.erb
<div class="form-group">
  <%= f.label :name %>:
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :description %>:
  <%= f.text_area :description, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :price %>:
  <%= f.number_field :price, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :status %>:
  <%= f.select :status, Product.status.options, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :quantity %>:
  <%= f.number_field :quantity, class: 'form-control' %>
</div>

<div id="uploaded-images">
  <%= render 'layouts/uploaded_images', record: @product %>
</div>

<div class="form-group">
  <%= f.label :images %>
  <%= f.file_field :images, multiple: true, class: 'form-control-file' %>
</div>

<div class="action">
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
</div>

app/views/products/edit.html.erb
<%= form_for @product, url: product_path(id: @product), method: :put do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/products/index.html.erb
<%= render 'layouts/search_form' %>
<h3>Products</h3>
<div class="row">
  <% @products.each do |product| %>
    <div class="card" style="width: 18rem;">
      <% if product.images.attached? %>
        <%= image_tag product.images.first.variant(resize: '100x180'), class: 'card-img-top', alt: 'Card image cap' %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title">
          <%= link_to product.name, product_path(product) %>
        </h5>
        <p class="card-text">
          <%= product.description %>
        </p>
        <% if current_user == product.seller %>
          <%= link_to 'edit', edit_product_path(product), class: 'btn btn-primary' %>
          <%= link_to 'destroy', product_path(product), method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @products %>

app/views/products/new.html.erb
<%= form_for @product, url: products_path do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/products/show.html.erb
<h3><%= @product.name %></h3>
<% if current_user %>
  <%= render 'layouts/fav_btn', favorable: @product %>
<% end %>
<p>$ <%= @product.price %> pt</p>
<p>Quantity: <%= @product.quantity %></p>
<p>Description: <%= @product.description %></p>
<p>Seller: <%= @product.seller_email %>
<% if current_user %>
  <%= render 'layouts/fav_btn', favorable: @product.seller %>
<% end %>
<p>
  <% if @product.images.attached? %>
    <% @product.images.each do |image| %>
      <%= link_to image_tag(image.variant(resize: '100x100')), image %>
    <% end %>
  <% end %>
</p>
</p>
<% if @product.quantity > 0 %>
  <p>
    <%= form_for @line_item, remote: true do |f| %>
      <%= f.number_field :quantity, value: 1, min: 1 %>
      <%= f.hidden_field :product_id, value: @product.id %>
      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
    <% end %>
  </p>
<% end %>