config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :carts
    resources :favorites
    resources :line_items
    resources :orders
    resources :orders_users
    resources :products

    root to: "users#index"
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "products#index"
  resources :products
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: :create
  resources :favorites, only: [:create, :destroy]
  resources :images, only: :destroy
  resources :avatars, only: :destroy
  namespace :my do
    resource :cart, only: [:show]
    resources :orders, only: [:index, :show]
    resources :sales_orders, only: [:index, :show]
    resources :favorite_sellers, only: :index
    resources :favorite_products, only: :index
  end
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_user&.cart&.line_items&.size} Items in Cart ( #{number_to_currency current_user&.cart&.total_price} )", my_cart_path, class: "btn btn-link" %>

app/views/layouts/_fav_btn.html.erb
<% unless current_user.my_favorites.exists?(favorable_type: favorable.model_name.to_s, favorable_id: favorable.id) %>
  <%= link_to "Add to favorite #{favorable.model_name}", favorites_path(favorable_id: favorable.id, favorable_type: "#{favorable.model_name}"), remote: true, method: :post, id: "fav_btn_#{favorable.model_name}_#{favorable.id}" %>
<% else %>
  <%= link_to "Remove from favorite #{favorable.model_name}", favorite_path(id: favorable.favorites.where(user_id: current_user.id).take.id, favorable_id: favorable.id, favorable_type: "#{favorable.model_name}"), remote: true, method: :delete, id: "fav_btn_#{favorable.model_name}_#{favorable.id}" %>
<% end %>

app/views/layouts/_search_form.html.erb
<%= form_tag({controller: 'products', action: 'index'}, method: :get) do %>
  Keywords <%= text_field_tag :keywords, params[:keywords] %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/layouts/_uploaded_images.html.erb
<% if record.images.attached? %>
  <% record.images.each do |image| %>
    <%= image_tag(image.variant(resize: '50x50')) %>
    <%= link_to 'Remove', image_path(image.id), remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div id="flash-div">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      </div>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<%= root_path %>">Auction</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hello, <%= current_user&.nickname || 'guest' %>
                <% if current_user&.avatar&.attached? %>
                  <%= image_tag(current_user.avatar.variant(resize: '50x50')) %>
                <% end %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= render 'devise/menu/login_menu' %>
                <%= render 'devise/menu/registration_menu' %>
                <div class="dropdown-divider"></div>
                <%= link_to 'Register your new product', new_product_path, class: 'dropdown-item' %>
                <% if current_user&.admin? %>
                  <%= link_to 'Admin', admin_products_path, class: 'dropdown-item' %>
                <% end %>
              </div>
            </li>
          </ul>
          <p class="cart-text"><%= render 'layouts/cart_text' %></p>
        </div>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>